### ISSUE TITLE
Invalid read of memory

### ISSUE THREAD

**Issue by msoos** [marijnheule/drat-trim#18] opened 2019-03-23 11:27 UTC
I am getting

```
==10348== Invalid read of size 4
==10348==    at 0x10F085: parse (in /usr/local/bin/drat-trim)
==10348==    by 0x10943A: main (in /usr/local/bin/drat-trim)
==10348==  Address 0xc0af7bc is 4 bytes before a block of size 112 alloc'd
==10348==    at 0x4839D7B: realloc (vg_replace_malloc.c:826)
==10348==    by 0x10E95E: parse (in /usr/local/bin/drat-trim)
==10348==    by 0x10943A: main (in /usr/local/bin/drat-trim)
```

Input CNF and DRAT attached.
[out.zip](https://github.com/marijnheule/drat-trim/files/2999277/out.zip)

Run as:

```
valgrind drat-trim out/fuzzTest_66.cnf out/fuzzTest-drat_43.cnf
```

This seems to be because of clause[ID], where ID is -1, which means we are 4 bytes before the malloc boundary (`int` is 4 bytes on this architecture), as warned by valgrind: `Address 0xc0af7bc is 4 bytes before a block of size 112 alloc'd`.

I am very confused why ID needs to be -1. Please try to fix before the SAT Race so that valid solvers don't get disqualified :) Thanks!

**Comment by marijnheule** [comment] 2023-02-28 00:45
Not sure what happened here. I cannot reproduce it with the current commit. ID shouldn't be -1. I assume it is fixed and will close this issue, but if you encounter it again, then I will look at it.

**Closed as completed by marijnheule** 2023-02-28 00:45 UTC
